{% set name = 'udunits2' %}
{% set version = '0.13' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

  script_env:
    - UDUNITS2_LIB


requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]
    - udunits2

  run:
    - r-base
    - udunits2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('udunits2')"  # [not win]
    - "\"%R%\" -e \"library('udunits2')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/pacificclimate/Rudunits2 https://www.unidata.ucar.edu/software/udunits/
  license: GPL-2
  summary: Provides simple bindings to Unidata's udunits library.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: udunits2
# Type: Package
# Title: Udunits-2 Bindings for R
# Version: 0.13
# Date: 2016-11-16
# Author: James Hiebert <hiebert@uvic.ca>
# Maintainer: James Hiebert <hiebert@uvic.ca>
# Description: Provides simple bindings to Unidata's udunits library.
# URL: https://github.com/pacificclimate/Rudunits2 https://www.unidata.ucar.edu/software/udunits/
# SystemRequirements: udunits-2
# License: GPL-2
# LazyLoad: yes
# Depends: R (>= 2.10.0)
# NeedsCompilation: yes
# Packaged: 2016-11-16 23:23:15 UTC; james
# Repository: CRAN
# Date/Publication: 2016-11-17 08:27:56

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
