{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-units
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.4_2"

source:
  fn: units_0.4-2.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/units_0.4-2.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/units/units_0.4-2.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: NISTunits, measurements, xml2, tibble, knitr, testthat, covr
requirements:
  build:
    - r-base
    - r-udunits2 >=0.13

  run:
    - r-base
    - r-udunits2 >=0.13

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('units')" # [not win]
    - "\"%R%\" -e \"library('units')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/edzer/units/
  license: GPL-2
  summary: Support for measurement units in R vectors; automatic propagation, conversion, derivation
    and simplification of units; raising errors in case of unit incompatibility. Compatible
    with the difftime class. Uses the UNIDATA udunits library and unit database for
    unit conversion and compatibility checking.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: units
# Version: 0.4-2
# Title: Measurement Units for R Vectors
# Authors@R: c(person("Edzer", "Pebesma", role = c("aut", "cre"), email = "edzer.pebesma@uni-muenster.de"), person("Thomas", "Mailund", role = "aut", email = "mailund@birc.au.dk"))
# Depends: R (>= 3.0.0)
# Imports: udunits2 (>= 0.13)
# Suggests: NISTunits, measurements, xml2, tibble, knitr, testthat, covr
# VignetteBuilder: knitr
# Description: Support for measurement units in R vectors; automatic propagation, conversion, derivation and simplification of units; raising errors in case of unit incompatibility. Compatible with the difftime class. Uses the UNIDATA udunits library and unit database for unit conversion and compatibility checking.
# LazyData: yes
# License: GPL-2
# URL: https://github.com/edzer/units/
# BugReports: https://github.com/edzer/units/issues/
# RoxygenNote: 5.0.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2017-01-13 08:07:21 UTC; edzer
# Author: Edzer Pebesma [aut, cre], Thomas Mailund [aut]
# Maintainer: Edzer Pebesma <edzer.pebesma@uni-muenster.de>
# Repository: CRAN
# Date/Publication: 2017-01-13 15:40:53

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
